# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=96, verbose_name='Otazka')),
                ('count', models.IntegerField(default=0, verbose_name='Pocet odpovedi')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='voting.Voting')),
            ],
        ),
    ]
